#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        # Stop and disable systemd service before files are deleted
        if [ -d /run/systemd/system ]; then
            systemctl stop elm-server || true
            systemctl disable elm-server || true
        fi
        ;;
    upgrade|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
